### PR TITLE
chore: auto set theme feature is missing

### PR DESCRIPTION
**Pull request by dengbo11**
dde-appearance depends org.deepin.dde.Timedate1(dde-session-daemon) service so it must depends org.dde.session.Daemon1.service

Log:

### CODE REVIEW

**Comment by dengbo11** [comment]
- fix https://github.com/linuxdeepin/developer-center/issues/5583

**Comment by Decodetalkers** [comment]
@justforlxz 
之前加了这个
```
WantedBy=graphical-session.target
```
是不是也顺便删掉好了？上次说不应该写

**Review by Decodetalkers — DISMISSED** [review]

**Review by Decodetalkers — APPROVED** [review]

**Pull request merged**
